name: Check Broken Links

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - canary
      - main
  workflow_dispatch:

jobs:
  url-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-links.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests colorama

    - name: Enable Color Output
      run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
      
    - name: Check for broken links
      id: check-links
      run: |
        python scripts/python/url-checker/url-checker.py
        if [ $? -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "No broken links found!"
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "Broken links were found!"
        fi
      continue-on-error: true

    - name: Upload log file
      uses: actions/upload-artifact@v4
      with:
        name: url-checker-log
        path: scripts/python/url-checker/logs/*.log

    - name: Clean up environment
      run: rm -rf scripts/python/url-checker/__pycache__

    - name: Create status badge
      run: |
        if [ "${{ steps.check-links.outputs.status }}" == "success" ]; then
          echo "STATUS_BADGE=passing" >> $GITHUB_ENV
          echo "STATUS_COLOR=brightgreen" >> $GITHUB_ENV
        else
          echo "STATUS_BADGE=failing" >> $GITHUB_ENV
          echo "STATUS_COLOR=red" >> $GITHUB_ENV
        fi
        
    - name: Update status badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: GIST_ID_FOR_BADGE
        filename: url-checker-status.json
        label: links
        message: ${{ env.STATUS_BADGE }}
        color: ${{ env.STATUS_COLOR }}
