name: Check Broken Links

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - canary
      - main
  workflow_dispatch:
    inputs:
      fail-on-broken-links:
        description: 'Fail workflow if broken links are found'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  url-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests colorama

    - name: Enable Color Output
      run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
      
    - name: Check for broken links
      id: check-links
      continue-on-error: true
      run: |
        python scripts/python/url-checker/url-checker.py
        EXIT_CODE=$?
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        if [ $EXIT_CODE -ne 0 ]; then
          echo "::warning::Broken links were found in the repository!"
        else
          echo "✅ No broken links found!"
        fi

    - name: Upload log file
      uses: actions/upload-artifact@v4
      with:
        name: url-checker-log
        path: scripts/python/url-checker/logs/*.log

    - name: Clean up environment
      run: rm -rf scripts/python/url-checker/__pycache__
      
    - name: Fail if broken links were found and failure is requested
      if: steps.check-links.outputs.exit_code != '0' && (github.event.inputs.fail-on-broken-links != 'false' || github.event_name != 'workflow_dispatch')
      run: |
        echo "::error::Broken links were found! See the logs for details."
        exit 1
