name: Check Broken Links

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - canary
      - main
  workflow_dispatch:
    inputs:
      fail-on-broken-links:
        description: 'Fail workflow if broken links are found'
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'

jobs:
  url-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests colorama

    - name: Enable Color Output
      run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
      
    - name: Check for broken links
      id: check_links
      run: |
        python scripts/python/url-checker/url-checker.py
        EXIT_CODE=$?
        echo "LINK_CHECK_EXIT_CODE=${EXIT_CODE}" >> $GITHUB_ENV
        
        # Always display the summary regardless of exit code
        echo "### URL Check Results" >> $GITHUB_STEP_SUMMARY
        if [ $EXIT_CODE -eq 0 ]; then
          echo "✅ All links are valid!" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Some broken links were found. Check the logs for details." >> $GITHUB_STEP_SUMMARY
          echo "Download the log artifacts for the complete report." >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: url-checker-log
        path: scripts/python/url-checker/logs/*.log

    - name: Clean up environment
      if: always()
      run: rm -rf scripts/python/url-checker/__pycache__
      
    - name: Determine if workflow should fail
      if: env.LINK_CHECK_EXIT_CODE != '0'
      run: |
        if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
          echo "SHOULD_FAIL=true" >> $GITHUB_ENV
        else
          echo "SHOULD_FAIL=${{ github.event.inputs.fail-on-broken-links }}" >> $GITHUB_ENV
        fi
        echo "SHOULD_FAIL=${SHOULD_FAIL}"

    - name: Debug workflow info
      if: env.LINK_CHECK_EXIT_CODE != '0'
      run: |
        echo "Exit code: ${{ env.LINK_CHECK_EXIT_CODE }}"
        echo "SHOULD_FAIL: ${{ env.SHOULD_FAIL }}"

    - name: Report final status
      if: env.LINK_CHECK_EXIT_CODE != '0' && env.SHOULD_FAIL == 'true'
      run: |
        echo "::error::Broken links were found in the documentation. See uploaded logs for details."
        exit 1
