name: Check Broken Links

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - canary
      - main
  workflow_dispatch:
    inputs:
      fail-on-broken-links:
        description: 'Fail workflow if broken links are found'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  url-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests colorama

    - name: Enable Color Output
      run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
      
    - name: Check for broken links
      id: check-links
      run: |
        python scripts/python/url-checker/url-checker.py
        echo "script_exit_code=$?" >> $GITHUB_OUTPUT
    
    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: url-checker-log
        path: scripts/python/url-checker/logs/*.log

    - name: Clean up environment
      if: always()
      run: rm -rf scripts/python/url-checker/__pycache__
      
    - name: Check results
      if: always()
      run: |
        if [ "${{ steps.check-links.outputs.script_exit_code }}" == "1" ]; then
          echo "::warning::Broken links were found in the repository!"
          
          # Only fail if this wasn't a manual run with the option set to false
          if [ "${{ github.event_name }}" != "workflow_dispatch" ] || [ "${{ github.event.inputs.fail-on-broken-links }}" != "false" ]; then
            echo "::error::Failing workflow because broken links were found!"
            exit 1
          else
            echo "::warning::Not failing workflow because 'fail-on-broken-links' was set to false."
          fi
        else
          echo "✅ No broken links found!"
        fi
