name: Check Broken Links

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - canary
      - main
  workflow_dispatch:
    inputs:
      fail-on-broken-links:
        description: 'Fail workflow if broken links are found'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  url-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests colorama

    - name: Enable Color Output
      run: echo "FORCE_COLOR=1" >> $GITHUB_ENV
      
    - name: Check for broken links
      id: check-links
      run: |
        # Run the script and capture both the output and exit code
        OUTPUT=$(python scripts/python/url-checker/url-checker.py 2>&1)
        EXIT_CODE=$?
        
        echo "$OUTPUT"
        
        # Count broken links by grep-ing the output
        BROKEN_ABSOLUTE=$(echo "$OUTPUT" | grep -c '\[BROKEN ABSOLUTE\]' || true)
        BROKEN_RELATIVE=$(echo "$OUTPUT" | grep -c '\[BROKEN RELATIVE\]' || true)
        TOTAL_BROKEN=$((BROKEN_ABSOLUTE + BROKEN_RELATIVE))
        
        echo "broken_absolute=$BROKEN_ABSOLUTE" >> $GITHUB_OUTPUT
        echo "broken_relative=$BROKEN_RELATIVE" >> $GITHUB_OUTPUT
        echo "total_broken=$TOTAL_BROKEN" >> $GITHUB_OUTPUT
        echo "script_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        
        # Save output to a file for artifact
        mkdir -p /tmp/url-checker-output
        echo "$OUTPUT" > /tmp/url-checker-output/output.log
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: url-checker-logs
        path: |
          scripts/python/url-checker/logs/*.log
          /tmp/url-checker-output/output.log

    - name: Clean up environment
      if: always()
      run: rm -rf scripts/python/url-checker/__pycache__
      
    - name: Determine status and fail if needed
      if: always()
      run: |
        BROKEN_LINKS=${{ steps.check-links.outputs.total_broken }}
        
        if [ "$BROKEN_LINKS" -gt "0" ]; then
          echo "::warning::Found $BROKEN_LINKS broken links (${{ steps.check-links.outputs.broken_absolute }} absolute, ${{ steps.check-links.outputs.broken_relative }} relative)."
          
          # Only fail if this wasn't a manual run with the option set to false
          if [ "${{ github.event_name }}" != "workflow_dispatch" ] || [ "${{ github.event.inputs.fail-on-broken-links }}" != "false" ]; then
            echo "::error::Failing workflow because broken links were found!"
            exit 1
          else
            echo "::warning::Not failing workflow because 'fail-on-broken-links' was set to false."
          fi
        else
          echo "✅ No broken links found!"
        fi
